### PR TITLE
Fix PHPUnit segfault in build checks with PHP 7.4

### PR DESCRIPTION
**Pull request by Ndiritu**

### CODE REVIEW

**Review by SilasKenneth — COMMENTED** [review]
This issue was already fixed. You should change xdebug to version 2. Please check the authentication repo for reference.

**Comment by Ndiritu** [comment]
> This issue was already fixed. You should change xdebug to version 2. Please check the authentication repo for reference.

Aah nice! Thought the fix was adding a memory limit.
Porting the fix over.

**Review by SilasKenneth — APPROVED** [review]

**Comment by Ndiritu** [comment]
@SilasKenneth I've set coverage to only run with PHP 8.0 and disabled coverage checks with other PHP versions since PHPUnit only throws the segmentation fault when Xdebug coverage is enabled and run with PHP 7.4

**Comment by SilasKenneth** [comment]
That looks okay for now. Eventually, we will have to drop support for PHP 7.4.

**Pull request merged**
